# This file is part of the ddd-symfony package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

script:
    - bin/phpspec run -fpretty

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm
    include:
        - php: 5.4
          env: COMPOSER_OPTIONS="--prefer-lowest"
