# This file is part of the ddd-symfony package.
#
# (c) Be単at Espi単a <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Be単at Espi単a <benatespina@gmail.com>

services:
    app.twig.loader:
        class: Twig_Loader_Filesystem
        arguments:
            - %twig_views_path%
        tags:
            - { name: twig.loader }
